### ISSUE TITLE
Crashes when watching a project running in docker

### ISSUE THREAD

**Issue by Mastermindzh** [dotnet/vscode-csharp#2408]
## Environment data
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     arch
 OS Version:
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.1 [/opt/dotnet/shared/Microsoft.NETCore.App]
```

VS Code version:
```
1.25.0-insider
368ab9c31b5c0930a40ab3f0e0d768ebbeeb9ef8
x64
```
**Also tried it on:**
```
1.24.1
24f62626b222e9a8313213fb64b10d741a326288
x64
```

C# Extension version: 1.15.2

## Steps to reproduce
1. Create Dockerfile:
```
    FROM microsoft/dotnet:2.1-sdk-stretch
    WORKDIR /app
    EXPOSE 5000
    CMD dotnet restore && dotnet watch run
```
2. Create docker-compose file
```
Compose:

    version: "3"
    services:
    
        web:
            build:
                context: ./api
                dockerfile: ./api/Dockerfile
            ports:
                - "5000:5000"
                - "5001:5001"
            volumes:
                - ./api/:/app
```
3. /api should contain a dotnet web api project. [The one I used (source @ bottom)](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1)

4. docker-compose build && docker-compose up

## Expected  behavior
Omnisharp to offer intellisense and formatting support in vscode

## Actual behavior
Omnisharp seems to crash and is generally really confused.

The project works, source code changes are picked up and the main data flow (adding / retrieving Todo items) also works. It's just that omnisharp stops working :(

## other stuff
I asked this on [StackOverflow](https://stackoverflow.com/questions/51152474/omnisharp-silently-crashes-when-working-with-docker) as well. It currently has no answers but that might change.
